/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package codexlatinus.frontend;

import codexlatinus.compiler.visualizacion.PasoPila;
import java.awt.*;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.*;

/**
 *
 * @author mauricio
 */
public class PanelPila extends javax.swing.JPanel {
    
    private final List<PasoPila> pasos;
    private int indice = 0;
    private JList<String> listaPila = new JList<>();
    private JTextArea areaLog = new JTextArea();
    /**
     * Creates new form PanelPila
     */
    public PanelPila(List<PasoPila> pasos)
    {
        this.pasos = pasos;
        setLayout(new BorderLayout());
        areaLog.setEditable(false);
        areaLog.setFont(new Font("Monospaced", Font.PLAIN, 12));
        JButton btnReiniciar = new JButton("Reiniciar");
        JButton btnAnterior = new JButton("Anterior");
        JButton btnSiguiente = new JButton("Siguiente");
        JButton btnIrFinal = new JButton("Ir al final");
        btnReiniciar.addActionListener(e -> reiniciar());
        btnAnterior.addActionListener(e -> retroceder());
        btnSiguiente.addActionListener(e -> avanzar());
        btnIrFinal.addActionListener(e -> irAlFinal());
        JPanel botonera = new JPanel();
        botonera.add(btnReiniciar);
        botonera.add(btnAnterior);
        botonera.add(btnSiguiente);
        botonera.add(btnIrFinal);
        JSplitPane split = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, new JScrollPane(listaPila), new JScrollPane(areaLog));
        split.setDividerLocation(300);
        add(split, BorderLayout.CENTER);
        add(botonera, BorderLayout.SOUTH);
        actualizar();
    }
    
    private void reiniciar()
    {
        if (pasos.isEmpty()) return;
        indice = 0;
        actualizar();
    }
    private void irAlFinal()
    {
        if (!pasos.isEmpty()) 
        {
            indice = pasos.size() - 1;
            actualizar();
        }
    }
    
    private void avanzar()
    {
        if (indice < pasos.size() - 1)
        {
            indice++;
            actualizar();
        }
    }
    private void retroceder()
    {
        if (indice > 0)
        {
            indice--;
            actualizar();
        }
    }
    private void actualizar()
    
    {
        if (pasos.isEmpty()) return;
        PasoPila paso = pasos.get(indice);
        List<String> pilaInvertida = new ArrayList<>(paso.getPila());
        Collections.reverse(pilaInvertida);
        listaPila.setListData(pilaInvertida.toArray(new String[0]));
        StringBuilder sbLog = new StringBuilder();
        for (int i = 0; i <= indice; i++)
        {
            sbLog.append(pasos.get(i).getAccion()).append("\n");
        }
        areaLog.setText(sbLog.toString());
        areaLog.setCaretPosition(areaLog.getDocument().getLength());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
