/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package codexlatinus.frontend;

import codexlatinus.CodexLatinusLexer;
import codexlatinus.CodexLatinusParser;
import codexlatinus.compiler.semantic.MiVisitor;
import codexlatinus.compiler.translation.PigLatinTraductor;
import codexlatinus.compiler.visualizacion.GeneradorASTDOT;
import codexlatinus.compiler.visualizacion.GeneradorSimbolosDOT;
import codexlatinus.compiler.visualizacion.ParseTraceListener;
import codexlatinus.compiler.visualizacion.PasoPila;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import org.antlr.v4.runtime.BaseErrorListener;
import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;
import org.antlr.v4.runtime.RecognitionException;
import org.antlr.v4.runtime.Recognizer;
import org.antlr.v4.runtime.tree.ParseTree;
import org.antlr.v4.runtime.tree.ParseTreeWalker;


public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());
    private List<PasoPila> pasos;
    private ParseTree arbolActual;
    private String codigoPig = "";
    private final LexerColoreado color = new LexerColoreado();
    private javax.swing.Timer timerColoreado;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        NumeroLineaVisual numerosLinea = new NumeroLineaVisual(editor, jScrollPane1);
        jScrollPane1.setRowHeaderView(numerosLinea);
        jScrollPane1.getVerticalScrollBar().addAdjustmentListener(e -> numerosLinea.actualizar());
        editor.setFont(new Font("Consolas", Font.PLAIN, 14));
        editor.setForeground(Color.BLACK);
        editor.setBackground(Color.WHITE);
        timerColoreado = new Timer(100, e -> color.aplicarResaltado(editor));
        timerColoreado.setRepeats(false);
        editor.getDocument().addDocumentListener(new javax.swing.event.DocumentListener()
        {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e)
            {
                reiniciarTimerResaltado();
                numerosLinea.actualizar();
            }
            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e)
            {
                reiniciarTimerResaltado();
                numerosLinea.actualizar();
            }
            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e)
            {
                reiniciarTimerResaltado();
                numerosLinea.actualizar();
            }
        });
        editor.setBackground(Color.WHITE);
        editor.setOpaque(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void reiniciarTimerResaltado()
    {
        timerColoreado.restart();
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnAbrirLat = new javax.swing.JButton();
        btnGuardarPig = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnCompilar = new javax.swing.JButton();
        btnTraducirPig = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnVerAST = new javax.swing.JButton();
        btnVerTablaSimbolos = new javax.swing.JButton();
        btnVerPila = new javax.swing.JButton();
        jSplitPane2 = new javax.swing.JSplitPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        editor = new javax.swing.JTextPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaAST = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        areaTabla = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaSalida = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 800));

        jToolBar1.setRollover(true);

        btnAbrirLat.setText("Abrir .lat");
        btnAbrirLat.setFocusable(false);
        btnAbrirLat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAbrirLat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAbrirLat.addActionListener(this::btnAbrirLatActionPerformed);
        jToolBar1.add(btnAbrirLat);

        btnGuardarPig.setText("Guardar .pig");
        btnGuardarPig.setFocusable(false);
        btnGuardarPig.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardarPig.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardarPig.addActionListener(this::btnGuardarPigActionPerformed);
        jToolBar1.add(btnGuardarPig);
        jToolBar1.add(jSeparator1);

        btnCompilar.setText("Compilar");
        btnCompilar.setFocusable(false);
        btnCompilar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCompilar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCompilar.addActionListener(this::btnCompilarActionPerformed);
        jToolBar1.add(btnCompilar);

        btnTraducirPig.setText("Traducir a Pig Latin");
        btnTraducirPig.setEnabled(false);
        btnTraducirPig.setFocusable(false);
        btnTraducirPig.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTraducirPig.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTraducirPig.addActionListener(this::btnTraducirPigActionPerformed);
        jToolBar1.add(btnTraducirPig);
        jToolBar1.add(jSeparator2);

        btnVerAST.setText("Ver AST");
        btnVerAST.setFocusable(false);
        btnVerAST.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVerAST.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVerAST.addActionListener(this::btnVerASTActionPerformed);
        jToolBar1.add(btnVerAST);

        btnVerTablaSimbolos.setText("Ver Tabla de SImbolos");
        btnVerTablaSimbolos.setFocusable(false);
        btnVerTablaSimbolos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVerTablaSimbolos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVerTablaSimbolos.addActionListener(this::btnVerTablaSimbolosActionPerformed);
        jToolBar1.add(btnVerTablaSimbolos);

        btnVerPila.setText("Ver Pila");
        btnVerPila.setFocusable(false);
        btnVerPila.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVerPila.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVerPila.addActionListener(this::btnVerPilaActionPerformed);
        jToolBar1.add(btnVerPila);

        jSplitPane2.setDividerLocation(600);
        jSplitPane2.setDividerSize(10);
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane2.setResizeWeight(0.8);

        jSplitPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jSplitPane1.setDividerLocation(600);
        jSplitPane1.setDividerSize(10);
        jSplitPane1.setToolTipText("");

        editor.setMinimumSize(new java.awt.Dimension(60, 300));
        editor.setPreferredSize(new java.awt.Dimension(60, 300));
        jScrollPane1.setViewportView(editor);

        jSplitPane1.setLeftComponent(jScrollPane1);

        areaAST.setColumns(20);
        areaAST.setRows(5);
        jScrollPane3.setViewportView(areaAST);

        jTabbedPane1.addTab("AST", jScrollPane3);

        areaTabla.setColumns(20);
        areaTabla.setRows(5);
        jScrollPane4.setViewportView(areaTabla);

        jTabbedPane1.addTab("Tabla de Simbolos", jScrollPane4);

        jSplitPane1.setRightComponent(jTabbedPane1);

        jSplitPane2.setLeftComponent(jSplitPane1);

        areaSalida.setColumns(20);
        areaSalida.setRows(5);
        areaSalida.setMinimumSize(new java.awt.Dimension(60, 500));
        areaSalida.setPreferredSize(new java.awt.Dimension(60, 500));
        areaSalida.setRequestFocusEnabled(false);
        jScrollPane2.setViewportView(areaSalida);

        jSplitPane2.setRightComponent(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSplitPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnAbrirLatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirLatActionPerformed
        JFileChooser fc = new JFileChooser();
        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION)
        {
            try
            {
                String contenido = Files.readString(fc.getSelectedFile().toPath());
                editor.setText(contenido);
                color.aplicarResaltado(editor);
            }
            catch (IOException e)
            {
                JOptionPane.showMessageDialog(this, "Error al abrir: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnAbrirLatActionPerformed

    private void btnGuardarPigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPigActionPerformed
        if (codigoPig.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "No hay código PigLatin generado para guardar.");
            return;
        }
        JFileChooser fc = new JFileChooser();
        fc.setSelectedFile(new File("salida.pig"));
        if (fc.showSaveDialog(this) == JFileChooser.APPROVE_OPTION)
        {
            try
            {
                Files.writeString(fc.getSelectedFile().toPath(), codigoPig);
            }
            catch (IOException e)
            {
                JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnGuardarPigActionPerformed

    private void btnCompilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompilarActionPerformed
        String codigo = editor.getText();
        areaSalida.setText("");
        areaAST.setText("");
        areaTabla.setText("");
        CharStream input = CharStreams.fromString(codigo);
        CodexLatinusLexer lexer = new CodexLatinusLexer(input);
        CommonTokenStream tokens = new CommonTokenStream(lexer);
        CodexLatinusParser parser = new CodexLatinusParser(tokens);
        parser.removeErrorListeners();
        
        parser.addErrorListener(new BaseErrorListener()
        {
            @Override
            public void syntaxError(Recognizer<?, ?> recognizer, Object offendingSymbol, int line, int charPositionInLine, String msg, RecognitionException e) 
            {
                areaSalida.append(String.format("Error sintáctico línea %d:%d - %s%n", line, charPositionInLine + 1, msg));
            }
        });
        ParseTree tree = parser.programa();
        if (parser.getNumberOfSyntaxErrors() > 0)
        {
            areaSalida.append("Se encontraron errores de sintaxis.\n");
            arbolActual = null;
            btnTraducirPig.setEnabled(false);
            return;
        }
        MiVisitor visitor = new MiVisitor();
        visitor.visit(tree);
        if (visitor.getErroresSemanticos() > 0)
        {
            areaSalida.append("Se encontraron " + visitor.getErroresSemanticos() + " errores semánticos.\n");
            arbolActual = null;
            btnTraducirPig.setEnabled(false);
            return;
        }
        this.arbolActual = tree;
        GeneradorASTDOT astGen = new GeneradorASTDOT();
        String astDOT = astGen.generarDOT(tree);
        areaAST.setText(astDOT);
        GeneradorSimbolosDOT simGen = new GeneradorSimbolosDOT();
        String simDOT = simGen.generarDOT(visitor.getTablaSimbolos());
        areaTabla.setText(simDOT);

        // Capturar pila de procesos
        ParseTreeWalker walker = new ParseTreeWalker();
        ParseTraceListener traceListener = new ParseTraceListener();
        walker.walk(traceListener, tree);
        this.pasos = traceListener.getPasos();

        areaSalida.setText("Programa válido. Se puede traducir a PigLatin.");
        btnTraducirPig.setEnabled(true);
    }//GEN-LAST:event_btnCompilarActionPerformed

    private void btnVerPilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPilaActionPerformed
        if (pasos == null || pasos.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Primero compila un programa válido para capturar la pila.");
            return;
        }
        PanelPila panel = new PanelPila(pasos);
        jTabbedPane1.addTab("Pila", panel);
        jTabbedPane1.setSelectedComponent(panel);
    }//GEN-LAST:event_btnVerPilaActionPerformed

    private void btnVerASTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerASTActionPerformed
        jTabbedPane1.setSelectedComponent(jScrollPane3);
    }//GEN-LAST:event_btnVerASTActionPerformed

    private void btnVerTablaSimbolosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerTablaSimbolosActionPerformed
        jTabbedPane1.setSelectedComponent(jScrollPane4);
    }//GEN-LAST:event_btnVerTablaSimbolosActionPerformed

    private void btnTraducirPigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraducirPigActionPerformed
        if (arbolActual == null)
        {
            JOptionPane.showMessageDialog(this, "Primero compila un programa válido antes de traducir.");
            return;
        }
        PigLatinTraductor traductor = new PigLatinTraductor();
        String pig = traductor.visit(arbolActual);
        this.codigoPig = pig;
        areaSalida.setText("Traducción a PigLatin:\n\n" + pig);
    }//GEN-LAST:event_btnTraducirPigActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaAST;
    private javax.swing.JTextArea areaSalida;
    private javax.swing.JTextArea areaTabla;
    private javax.swing.JButton btnAbrirLat;
    private javax.swing.JButton btnCompilar;
    private javax.swing.JButton btnGuardarPig;
    private javax.swing.JButton btnTraducirPig;
    private javax.swing.JButton btnVerAST;
    private javax.swing.JButton btnVerPila;
    private javax.swing.JButton btnVerTablaSimbolos;
    private javax.swing.JTextPane editor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
